version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: copart-notifier
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./copart-notifier.sqlite:/app/copart-notifier.sqlite
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:3000/api',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
